repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        files: '\.po$'
      - id: trailing-whitespace
        files: '\.po$'
      - id: check-merge-conflict
  - repo: https://github.com/sphinx-contrib/powrap
    rev: v1.0.2
    hooks:
      - id: powrap
        args: [--check, --quiet]
        files: '\.po$'
